### ISSUE TITLE
RESTful API (polls)

### ISSUE THREAD

**Issue by adophilus** [CyberRocketTeam/poller#2]
- [ ] route to create polls (POST /poll/create)
- [ ] route to retrieve polls
  - [ ] GET `/poll` (to get list of polls)
  - [ ] GET `/poll/<poll_id>` (to get a specific poll)
- [ ] route to update polls (PUT `/poll/<poll_id>`)
- [ ] route to delete polls (DELETE `/poll/<poll_id>`)

**Comment by CyberRocketTeam** [comment]
The issue has been resolved
